### ISSUE TITLE
Is there any randomness/non-determinism in OSQP?

### ISSUE THREAD

**Issue by dzdang** [osqp/osqp#583] opened 2023-09-11 07:37 UTC
Hi,

I'm currently working with a simulation codebase that uses OSQP. I'm trying to debug a non-determinism issue in the codebase (for repeated runs of the simulation code, it gives slightly different results). I'm quite sure the randomness is coming from somewhere within OSQP. 

The OSQP solver is initialized as shown in https://osqp.org/docs/interfaces/python.html. For the same inputs into the OSQP solver, it appears that different results are produced. Could someone advise on how to make this deterministic? 

Thanks,
David

**Comment by goulart-paul** [comment] 2023-09-11 07:54
The issue is that the solver makes matrix factorization updated based on how long the initial factorization takes relative to the time per iteration.   Slightly different run times for the same problem can therefore lead to different behaviour.

You can set the solver to instead consider factorization updates only at fixed intervals, e.g. every 25 or 50 iterations.   Do this by setting `adaptive_rho_interval` to some integer value.

See also here: https://github.com/osqp/osqp-python/issues/116

**Comment by dzdang** [comment] 2023-09-11 08:08
Ah I see, thanks. Is `adaptive_rho_interval` an attribute of the `OSQP` class? I'm not sure where to set it.

**Comment by goulart-paul** [comment] 2023-09-11 08:09
It's just one of the options in the settings structure.   See here: https://osqp.org/docs/interfaces/solver_settings.html

**Comment by wurui90** [comment] 2023-09-22 01:56
After setting adaptive_rho_interval to 25, we now get deterministic results. Thanks very much for the guidance!

**Comment by wurui90** [comment] 2023-09-22 17:10
> It's just one of the options in the settings structure. See here: https://osqp.org/docs/interfaces/solver_settings.html

Hi Goulart, thanks very much for your pointers!

Btw, there is no detailed explanation of the setting fields in https://osqp.org/docs/interfaces/solver_settings.html. Is there a page that explains what does the setting field detailed meanings? Thanks!

**Comment by wurui90** [comment] 2023-09-25 16:40
Got it. Thanks a lot!

**Closed** 2023-09-25 16:42 UTC

**Comment by ae2a2** [comment] 2023-11-13 18:43
> The issue is that the solver makes matrix factorization updated based on how long the initial factorization takes relative to the time per iteration. Slightly different run times for the same problem can therefore lead to different behaviour.

Does the frequency of updates result in a different convergence criterion? It seems it does because when I set updates at 25 iterations, that results are appreciably different.

**Comment by goulart-paul** [comment] 2023-11-13 19:36
The convergence criteria, i.e. the test we use to determine whether to stop, does not change.   The converge *rate* might change because the solver tries to dynamically compute an update to the "rho" parameter to try to speed up convergence.   

Having more iterations between updates gives the internal estimate of the best "rho" a better chance to stabilise to a good guess, but at the cost of doing more iterations (possibly with slow improvement) between updates.   Having fewer iterations has the opposite effect.

The suggestion of 25 for that parameter is just a general rule of thumb and seems to work on a wide variety of problems.   For your particular problem the best choice might be different (50 say).
