### ISSUE TITLE
Simple trajectory optimisation that fails

### ISSUE THREAD

**Issue by jmainpri** [osqp/osqp#410] opened 2022-03-22 10:23 UTC
Hi there,

I am testing a problem involving a simple band diagonal quadric objective subject to bounds on the variables and two equality constraints. It seems that this problem is trivial enough that it should work with the default parameters, as it is indeed the case for the quadprog implementations available online.

I found that the default "check_termination: on (interval 25)" seems to be the problem.

Maybe you are interested to look into this. Feel free to add it to your example collection:

https://github.com/humans-to-robots-motion/bewego/blob/b7a88cbfdc2729c78410de42100bccfbe646a1c2/examples/osqp_trajopt.py#L22

Best regards,
-- Jim

Version  OSQP v0.6.2 (Mac OS X)

**Comment by goulart-paul** [comment] 2022-03-22 10:35
The issue is just that the default solver settings have convergence tolerances that are looser than what you are checking for in the final assertion of your example.   The solver has `eps_rel = eps_abs = 1e-3` by default, and you are testing for more accuracy than that will give you.  

Two options you can try: 

- Just set higher tolerances for `eps_rel` and `eps_abs`.   Even setting these to 1e-8 (which is quite extreme for a first order solver like OSQP), the solver still converged for me in 100 iterations on this problem.   
- Keep things as they are but add the option `polish = True`.   This produces a solution to very high accuracy when it works, which it did for me in the example you provided.

**Comment by jmainpri** [comment] 2022-03-22 11:43
Super, 

I set eps_rel = eps_abs = 1e-6 and made the test a little bit easier =)
I should look into a better way to derive the test bounds directly next time.

Thanks for the quick help.

**Comment by goulart-paul** [comment] 2022-04-01 18:26
Glad it worked out.   I will close this - feel free to reopen if the problem is not resolved.

**Closed by goulart-paul** 2022-04-01 18:26 UTC
